# Generated by Django 4.2.23 on 2025-11-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
