# Generated by Django 4.2.23 on 2025-11-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="shipping_adderss",
            new_name="shipping_address",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("paid", "Pago"),
                    ("failed", "Falhou"),
                    ("refunded", "Reembolsado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("confirmed", "Confirmado"),
                    ("processing", "Em Processamento"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregue"),
                    ("cancelled", "Cancelado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("reference", "Pagamento por Referência"),
                    ("mobile", "Pagamento Móvel"),
                    ("card", "Pagamento com Cartão"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("processing", "Em Processamento"),
                    ("completed", "Concluído"),
                    ("failed", "Falhou"),
                    ("refunded", "Reembolsado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
