# Generated by Django 4.2.23 on 2025-11-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_shipping_adderss_order_shipping_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
