# Generated by Django 4.2.23 on 2025-11-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_approved_seller",
            field=models.BooleanField(default=True),
        ),
    ]
