# Generated by Django 4.2.23 on 2025-11-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_is_approved_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_approved_seller",
            field=models.BooleanField(default=False),
        ),
    ]
