# Generated by Django 4.2.23 on 2025-11-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Ruim"),
                    (2, "Regular"),
                    (3, "Bom"),
                    (4, "Muito Bom"),
                    (5, "Excelente"),
                ]
            ),
        ),
    ]
